import { z } from "zod";

// Building blocks for app-config and for every package's settings schema, so the same
// kind of value is checked the same way everywhere.

export const hexColor = z
  .string()
  .regex(/^#[0-9A-Fa-f]{6}$/, "Use a colour like #42523D");

// Every address in a settings file is HTTPS, including in local development (the dev tunnel).
export const httpsUrl = z.url({ protocol: /^https$/ });

// Runtime releases and package versions, e.g. "1.0.0".
export const semver = z
  .string()
  .regex(/^\d+\.\d+\.\d+$/, "Use a version like 1.0.0");

// Lowercase id with dashes, e.g. "product-row". Used for package, preset and plan ids.
export const slug = z
  .string()
  .max(64)
  .regex(/^[a-z][a-z0-9]*(-[a-z0-9]+)*$/, "Use lowercase letters, digits and dashes");

// Id of one section or block inside a design, generated by the editor.
export const nodeId = z.string().regex(/^[A-Za-z0-9_-]{1,64}$/);

export const myshopifyDomain = z
  .string()
  .regex(/^[a-z0-9][a-z0-9-]*\.myshopify\.com$/, "Expected a *.myshopify.com domain");

// Shopify API versions are date-based and released each quarter, e.g. "2026-07"
// (https://shopify.dev/docs/api/usage/versioning).
export const shopifyApiVersion = z
  .string()
  .regex(/^\d{4}-(01|04|07|10)$/, "Expected an API version like 2026-07");

// ISO 3166-1 alpha-2, the codes in Shopify's CountryCode enum, e.g. "US" or "IN".
export const countryCode = z
  .string()
  .regex(/^[A-Z]{2}$/, "Expected a two-letter country code like US");

// Global ID of a Shopify object, e.g. gid://shopify/Collection/123
// (https://shopify.dev/docs/api/usage/gids).
export function shopifyGid(type: string) {
  return z
    .string()
    .regex(new RegExp(`^gid://shopify/${type}/\\d+$`), `Expected a Shopify ${type} ID`);
}
